### PR TITLE
docs: fix watch mode for JS

### LINKED ISSUE #9041: docs build-site.sh maxes out CPU in continuous mode
This seems unnecessary.

### PR DESCRIPTION
**Pull request by alxndrsn**
* remove `buildJekyll()` path check, because `path` is not the argument that `watchGlob()` passes to the listener
* update watched paths for `buildJekyll()` to only listen for jekyll-relevant paths
* use async watcher functions so that promises are returned

Closes #9041

### CODE REVIEW

File: bin/build-site.js [hunk 1]
```diff
@@ -73,8 +73,15 @@ if (!process.env.BUILD) {
   const http_server = require('http-server');
   const watchGlob = require('glob-watcher');
 
-  watchGlob('**', buildJekyll);
+  watchGlob('!(_site)/**', buildJekyll);
```
Comment (alxndrsn) [inline bin/build-site.js:76]: This should already be handled by:

https://github.com/pouchdb/pouchdb/blob/8f388436e1d0d2f9e4d7bb18c82a9d54864b42d6/bin/build-site.js#L33-L36

It's probably worth understanding why that isn't good enough.

Comment (alxndrsn) [reply bin/build-site.js:76]: ...because the arg passed to glob watchers is not the path of the changed file

File: bin/build-site.js [hunk 2]
```diff
@@ -73,8 +69,15 @@ if (!process.env.BUILD) {
...
```
Comment (alxndrsn) [inline bin/build-site.js:72]: this glob doesn't expand as expected

**Comment by SourceR85** [comment]
Can you resolve that conflict in build-site?

**Review by SourceR85 — APPROVED** [review]
LGTM
